[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py migrate']

[start]
cmd = 'gunicorn videolang_backend.wsgi' 