# Generated by Django 5.1.6 on 2025-02-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_service', '0002_video_visual_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
